# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox"

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = true
  end

  config.vm.hostname = ws-test

  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "../local.yml"
    ansible.inventory_path = "hosts"
  end

end
