# Preliminary tasks to run before roles
# Temporarily removed due to apt update failing with following errors:
#
# Err:13 https://packages.cloud.google.com/apt kubernetes-xenial Release
#  404  Not Found [IP: 172.253.124.113 443]
# Reading package lists... Done
# E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' no longer has a Release file.
# N: Updating from such a repository can't be done securely, and is therefore disabled by default.
# N: See apt-secure(8) manpage for repository creation and user configuration details.
#
#   become: true
#   pre_tasks:
#     - name: pre-run | update package cache (debian, etc)
#       tags: always
#       apt: update_cache=yes
#       changed_when: False
#       when: ansible_distribution in ["Debian", "Ubuntu"]

# Provision dev machines
- hosts: dev
  become: true
  roles:
    - core
    - desktop
    - vim
    - terraform
    - geerlingguy.docker
    - nvm
    - go
    - k8s
    - flutter

# End of run cleanup
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
