---
# Ansible user setup
- name: "users | create ansible user"
  user:
    name: ansible
    system: yes
    shell: /sbin/nologin

- name: "users | copy sudoers_ansible"
  copy:
    src: sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: "users | create log directory for ansible user"
  file:
    path: "/var/log/ansible"
    state: directory
    owner: ansible
    group: ansible
    mode: 0755

- name: "users | copy provisioning script"
  copy:
    src: provision.sh
    dest: /home/ansible/provision.sh
    owner: ansible
    group: ansible
    mode: 0700

- name: "users | cron job for ansible-pull"
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/home/ansible/provision.sh"

# Primary user setup (user should have already been created prior to provisioning)
- name: "users | {{ username }} | remove pre-installed home dirs"
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: absent
  with_items:
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: "users | {{ username }} | setup home directories"
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
  with_items:
    - bin
    - desktop
    - documents
    - downloads
    - music
    - pictures
    - public
    - src
    - templates
    - videos
    - .config/zshrc

- name: "users | {{ username }} | set user-dirs.dirs"
  copy:
    src: user-dirs.dirs
    dest: "/home/{{ username }}/.config/user-dirs.dirs"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
  notify: update_xdg
