---
- name: flutter and dart
  community.general.snap:
    name: flutter
    classic: yes

- name: apt package dependencies
  apt:
    name:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev

- name: zsh config
  copy:
    src: flutterrc.zsh
    dest: "/home/{{ username }}/.config/zshrc/flutterrc.zsh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# TODO: setup Android studio/emulator (dl and untar to /opt)
# For now, just do it manually following these instructions:
# https://docs.flutter.dev/get-started/install/linux#android-setup
